version: 4.0.{build}

branches:

  only:
  - master

image: Visual Studio 2019

configuration: Release

platform: Any CPU

before_build:

- cmd: nuget restore source/AvalonDock.sln

build:

  verbosity: minimal

test: off

artifacts:

- path: source\MVVMTestApp\bin\Release
  name: MVVMTestApp

- path: source\TestApp\bin\Release
  name: TestApp

- path: source\WinFormsTestApp\bin\Release
  name: WinFormsTestApp

- path: source\MLibTest\MLibTest\bin\Release
  name: MLibTest

- path: source\Components\AvalonDock\bin\Release
  name: Dirkster.AvalonDock

- path: source\Components\AvalonDock.Themes.VS2013\bin\Release
  name: Dirkster.AvalonDock.Themes.VS2013

- path: source\Components\AvalonDock.Themes.Aero\bin\Release
  name: Dirkster.AvalonDock.Themes.Aero

- path: source\Components\AvalonDock.Themes.Expression\bin\Release
  name: Dirkster.AvalonDock.Themes.Expression

- path: source\Components\AvalonDock.Themes.Metro\bin\Release
  name: Dirkster.AvalonDock.Themes.Metro

- path: source\Components\AvalonDock.Themes.VS2010\bin\Release
  name: Dirkster.AvalonDock.Themes.VS2010
