<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <RootNamespace>AvalonDock.Themes</RootNamespace>
    <TargetFrameworks>netcoreapp3.0;net5.0-windows;net48</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <SignAssembly>True</SignAssembly>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>4.72.1</Version>
    <AssemblyVersion>4.72.1</AssemblyVersion>
    <FileVersion>4.72.1</FileVersion>
    <PackageVersion>4.72.0</PackageVersion>
    <Company>Open Source</Company>
    <Product>ML592.AvalonDock.Themes.VS2022</Product>
    <Copyright>2017-2023</Copyright>
    <Description>This assembly implements a docking layout system for WPF.</Description>
    <PackageProjectUrl>https://github.com/MLing592/avalonDock-for-WPF</PackageProjectUrl>
    <RepositoryUrl>https://github.com/MLing592/avalonDock-for-WPF</RepositoryUrl>
    <PackageId>ML592.AvalonDock.Themes.VS2022</PackageId>
    <Authors>ML592</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <AssemblyOriginatorKeyFile>sn.snk</AssemblyOriginatorKeyFile>
    <DelaySign>False</DelaySign>
    <Title>ML592.AvalonDock.Themes.VS2022</Title>
    <PackageReadmeFile>readme-nuget.md</PackageReadmeFile>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="**\*.png" />
  </ItemGroup>

  <!-- NuGet Packaging -->
  <ItemGroup>
    <None Include="..\..\..\docs\readme-nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvalonDock\AvalonDock.csproj" />
  </ItemGroup>
</Project>
